services:
 db:
   image: postgres:15
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USERNAME}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     # POSTGRES_HOST_AUTH_METHOD: "trust"
   # command: ["postgres", "-p", "5435"]
   ports:
     - "5435:5432"
   volumes:
      - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env

 restaurantfinder-web:
   build: .
   container_name: restaurant-finder
   ports:
     - "8000:8000"
   depends_on:
     - db
   command: ["./init_app_data.sh"]
   volumes:
     - .:/Liine
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
     DATABASE_ENGINE: ${DATABASE_ENGINE}
     DATABASE_NAME: ${DB_NAME}
     DATABASE_USERNAME: ${DB_USERNAME}
     DATABASE_PASSWORD: ${DB_PASSWORD}
     DATABASE_HOST: db
     DATABASE_PORT: ${HOST_PORT}
   env_file:
     - .env
volumes:
   postgres_data: