networks:
  frontend_net:

services:
 db:
   image: postgres:15
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USERNAME}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     #POSTGRES_HOST_AUTH_METHOD: "trust"
     PG_PORT: 5435
   healthcheck:
     test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
     interval: 5s
     timeout: 5s
     retries: 5
   command: ["postgres", "-p", "5435"]
   ports:
     - "5435:5435"
   networks:
     - frontend_net
   volumes:
     - ./data/restaurants.csv:/docker-entrypoint-initdb.d/restaurants.csv
     - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
#     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env

 django-web:
   build: .
   container_name: restaurant-finder
   ports:
     - "8000:8000"
   depends_on:
     - db
   # command: ["python", "data/etl_script.py", "-rawtable"]
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
     DATABASE_ENGINE: ${DATABASE_ENGINE}
     DATABASE_NAME: ${DB_NAME}
     DATABASE_USERNAME: ${DB_USERNAME}
     DATABASE_PASSWORD: ${DB_PASSWORD}
     DATABASE_HOST: '0.0.0.0'
     DATABASE_PORT: ${HOST_PORT}
   networks:
     - frontend_net
   env_file:
     - .env
volumes:
   postgres_data: