BEGIN;
--
-- Create model Restaurants
--
CREATE TABLE "restaurantfinder_restaurants" (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "restaurant_ops" jsonb NOT NULL
    );
COMMIT;
