DO $$
BEGIN

IF EXISTS (SELECT FROM pg_tables WHERE tablename = 'restaurants_raw') THEN
        RAISE NOTICE 'Table restaurants_raw already exists! Aborting ETL process.';
    ELSE
        CREATE TABLE restaurants_raw (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            "Restaurant Name" VARCHAR(100) NOT NULL,
            "Hours" VARCHAR(200) NOT NULL
        );
        RAISE NOTICE 'Table restaurants_raw has been created!';

    END IF;
END $$;
