BEGIN;
--
-- Create raw table Restaurants
--
CREATE TABLE "restaurants_raw"
(
"id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
"Restaurant Name" VARCHAR(100) NOT NULL,
"Hours" VARCHAR(200) NOT NULL
);
COPY restaurants_raw("Restaurant Name", "Hours")

FROM '/tmp/restaurants.csv'
DELIMITER ',' CSV HEADER;
COMMIT;

-- FROM '/docker-entrypoint-initdb.d/restaurants.csv'